extends:
- airbnb
- plugin:react/recommended

plugins:
- react
- jsx-a11y
- import
env:
  browser: true
  es6: true
  node: true
parser: babel-eslint
globals:
  __DEBUG__: true
  __WEBPACK__: true
  __VERSION__: true
parserOptions:
  ecmaFeatures:
    # enable JSX support
    jsx: true
rules:
  # use only single quotes/backquotes for strings
  quotes: ["error", "single"]
  # trailing commas are mandatory
  comma-dangle: ["error", "always-multiline"]
  # indentation made with spaces not tabs
  indent: ["error", 4, { "ignoreComments": true }]
  # lines are max. 100 signs long
  max-len: ["error", { "code": 100 }]
  # a line ends with semicolon, period
  semi: ["error", "always"]
  # addon to 'semi', cares about spaces before and after semicolon usage
  semi-spacing: ["error", {"before": false, "after": true}]
  prefer-destructuring: ["warn"]
  no-multi-spaces: ["error"]
  yoda: ["error"]
  no-multiple-empty-lines: ["error"]
  no-trailing-spaces: ["error"]
  no-unneeded-ternary: ["error"]
  "require-jsdoc": [
    "error",
    {
      "require": {
        "FunctionDeclaration": false,
        "MethodDefinition": true,
        "ClassDeclaration": true,
        "ArrowFunctionExpression": false,
        "FunctionExpression": false
      }
    }
  ]
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-use-before-define: ["error"]
  no-warning-comments: [
    "warn",
    {
      "terms": ["todo", "fixme", "xxx", "to do", "fix me"]
    }
  ]
  import/no-extraneous-dependencies: [
    "error",
    {
      "devDependencies": [
        "./buildConfig.js",
        "./gulpfile.js",
        "**/*.test.js",
        "**/*.spec.js",
        "ui-test/**/*",
        "test/**/*"
      ]
    }
  ]
  # limit the max amount of conditionals
  complexity: ["error", { "max": 4 }]
  # allow functions with a maximum of 50 lines
  max-lines-per-function: ["error", { "max": 50, "skipBlankLines": true, "skipComments": true}]
  react/jsx-no-bind: ["warn"]
  react/forbid-prop-types: ["warn"]
  react/prefer-es6-class: ["warn"]
  react/prop-types: ["warn"]
  react/require-default-props: ["warn"]
  react/sort-comp: ["warn"]
  react/jsx-boolean-value: ["off"]
  # align closing react component bracket with opening bracket
  react/jsx-closing-bracket-location: [1, "line-aligned"]
