const aliases = {
    'ecc-component-annotationview': '@eccenca/module-annotation',
    'ecc-component-editor': '@eccenca/component-editor',
    'ecc-component-footer': '@eccenca/component-footer',
    'ecc-component-graphlist': '@eccenca/component-graphlist',
    'ecc-component-helpscreen': '@eccenca/module-about',
    'ecc-component-historymanager': '@eccenca/component-historymanager',
    'ecc-component-licenses': '@eccenca/component-licenses',
    'ecc-component-linkpartner': '@eccenca/component-linkpartner',
    'ecc-component-login': '@eccenca/component-login',
    'ecc-component-navigation': '@eccenca/component-navigation',
    'ecc-component-objectview': '@eccenca/component-objectview',
    'ecc-component-outputdefinition': '@eccenca/component-outputdefinition',
    'ecc-component-priips': '@eccenca/component-priips',
    'ecc-component-queryeditor': '@eccenca/component-queryeditor',
    'ecc-component-rdfdoc': '@eccenca/component-rdfdoc',
    'ecc-component-resourcelist': '@eccenca/component-resourcelist',
    'ecc-component-resourcelist2': '@eccenca/component-resourcelist2',
    'ecc-component-resourceselect': '@eccenca/component-resourceselect',
    'ecc-component-resourcetimeline': '@eccenca/component-resourcetimeline',
    'ecc-component-resourceview': '@eccenca/component-resourceview',
    'ecc-component-searchinput': '@eccenca/component-searchinput',
    'ecc-component-sketch': '@eccenca/component-sketch',
    'ecc-component-sourceview': '@eccenca/component-sourceview',
    'ecc-component-subscriptionmanagement':
        '@eccenca/component-subscriptionmanagement',
    'ecc-component-sunburst': '@eccenca/component-sunburst',
    'ecc-component-terminput': '@eccenca/component-terminput',
    'ecc-component-usageview': '@eccenca/component-usageview',
    'ecc-component-usersupport': '@eccenca/component-usersupport',
    'ecc-component-vocabmanager': '@eccenca/module-vocabmanager',
    'ecc-component-webvowl': '@eccenca/component-webvowl',
    'ecc-dotfiles': '@eccenca/dotfiles',
    'ecc-gui-elements': '@eccenca/gui-elements',
    'ecc-gulp-tasks': '@eccenca/gulp-tasks',
    'ecc-license-checker': '@eccenca/license-checker',
    'ecc-messagebus': '@eccenca/messagebus',
    'ecc-middleware-defaultgraph': '@eccenca/middleware-defaultgraph',
    'ecc-mixins': '@eccenca/mixins',
    'ecc-queryutils': '@eccenca/queryutils',
    'ecc-resparqler': '@eccenca/resparqler',
    'ecc-store-auth': '@eccenca/store-auth',
    'ecc-store-sparql': '@eccenca/store-sparql',
    'ecc-store-titlehelper': '@eccenca/store-titlehelper',
    'ecc-superagent': '@eccenca/superagent',
    'ecc-utils': '@eccenca/utils',
    'ecc-validation-helpers': '@eccenca/validation-helpers',
    // Only for testing purposes in this repository
    'ecc-test': 'lodash',
};

module.exports = aliases;
